### ISSUE TITLE
Add support for SG5.0RS

### ISSUE THREAD

**Issue by bohdan-s** [bohdan-s/SungrowModbusWebClient#3]
See: https://github.com/bohdan-s/SunGather/issues/31

**Comment by bohdan-s** [comment]
Changed websocket request from runtime to devicelist
Removing the requirement of static look up of model
Implemented in v0.3.2

**Comment by puijken** [comment]
This got my SG5.0RS reporting, thanks a lot!
However the SG5.0RS has 2 MPPT strings but on level 2 it only reports 1 string - probably because it is a "unsupported" device which just uses default parameters I guess .. I will still try and get you the modbus map if I ever get it!

EDIT: also the current power is not scraped I think - gives an error message for pvoutput - will check tomorrow when the sun is up!

`PVOutput: Configured to use total_active_power but not configured to scrape this register`

**Comment by puijken** [comment]
Possible type code?

`2022-03-06 00:53:14 WARNING  Unknown Type Code Detected: 9734`

9734 to hex = 0x2606

**Comment by bohdan-s** [comment]
Perfect,

If you could have a look at the PV Communications PDF in issue #31, and let me know what it supports I will add your Inverter in as supported, with what we think it supports while we wait to see if SunGrow will give us the map.

I am thinking of making it match the SG5.0RT model?

**Comment by puijken** [comment]
It's probably close - if the model numbers would indicate anything. In any case THE one difference would be single phase for the RS and tripe phase for the RT - so the RS will not report anything for phase2 and phase3.

If you have implemented the change I will post an ouput of level2 (or level3?) so we can verify what values are and are not reporting values.

Thanks again - swift replies and solutions !

**Comment by puijken** [comment]
Messed around a little bit with a changed registers.yaml file - following output in the web interface:
(just did a find/replace SG5.0RT with SG5.0RS except for phase2 and phase3 outputs)

```
Sungather v0.3.5
Address
Register	Value
----	device_type_code	SG5.0RS
----	run_state	ON
5001	nominal_active_power	5.0 kW
5002	output_type	2P
5003	daily_power_yields	20.2 kWh
5004	total_power_yields	66.4 kWh
5006	total_running_time	37 h
5008	internal_temperature	0.0 °C
5009	total_apparent_power	0 VA
5011	mppt_1_voltage	0.0 V
5012	mppt_1_current	0.0 A
5013	mppt_2_voltage	0.0 V
5014	mppt_2_current	0.0 A
5017	total_dc_power	0 W
5019	phase_a_voltage	0.0 V
5022	phase_a_current	0.0 A
5031	total_active_power	0 W
5033	total_reactive_power	0 Var
5035	power_factor	0.0
5036	grid_frequency	0.0 Hz
5038	work_state_1	Standby
5049	nominal_reactive_power	3.0 kVar
5071	array_insulation_resistance	2412 k-ohm
5077	active_power_regulation_setpoint	5000 W
5079	reactive_power_regulation_setpoint	0 Var
5081	work_state_2	16
5113	daily_running_time	652 min
5128	monthly_power_yields	66.4 kWh
5146	negative_voltage_to_the_ground	0.0 V
5147	bus_voltage	0.0 V
5150	pid_work_state	0
5151	pid_alarm_code	0
5216	export_power	0
5218	power_meter	0
7013	string_1_current	0.0 A
7014	string_2_current	0.0 A
7026	string_14_current	0.0 A
5006	start_stop	Start
5007	power_limitation_switch	Enable
5008	power_limitation_setting	100.0 %
5019	power_factor_setting	0.0
5035	night_svg_switch	Disable
5036	reactive_power_adjustment_mode	Off
5037	reactive_power_percentage_setting	0.0 %
5039	power_limitation_adjustment	5.0 kW
5040	reactive_power_adjustment	0.0 kVar
5041	pid_recovery	Disable
----	export_to_grid	0 W
----	import_from_grid	0 W
----	timestamp	2022-3-6 21:16:53
```

Probably a decent start - the sun's already down today of course but will check again tomorrow what these values show when the invertor is running.

**Comment by bohdan-s** [comment]
support added via: https://github.com/bohdan-s/SunGather/issues/31
